INSERT IGNORE INTO team (sos, status, team_colour) VALUES (0, "OFF_DUTY", 'Magenta');
INSERT IGNORE INTO team (sos, status, team_colour) VALUES (0, "OFF_DUTY", 'Ultraviolet');
INSERT IGNORE INTO team (sos, status, team_colour) VALUES (0, "OFF_DUTY", 'Purple');
INSERT IGNORE INTO team (sos, status, team_colour) VALUES (0, "OFF_DUTY", 'Blue');
INSERT IGNORE INTO team (sos, status, team_colour) VALUES (0, "OFF_DUTY", 'Aqua');
INSERT IGNORE INTO team (sos, status, team_colour) VALUES (0, "OFF_DUTY", 'Green');
INSERT IGNORE INTO team (sos, status, team_colour) VALUES (0, "OFF_DUTY", 'Red');
INSERT IGNORE INTO team (sos, status, team_colour) VALUES (0, "OFF_DUTY", 'Orange');
INSERT IGNORE INTO team (sos, status, team_colour) VALUES (0, "OFF_DUTY", 'Yellow');